name: login_demo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.7
  flutter: ^3.38.7

dependencies:
  bloc: ^9.2.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  intl: ^0.20.2
  meta: ^1.17.0
  

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
